project:
  type: website
  output-dir: docs
  
website:
  title: "Jessica French"
  favicon: "images/trillium-flower-png.png"
  navbar:
      left:
        - href: index.qmd
          text: Home
        - href: about.qmd
          text: About
        - href: code_examples.qmd
          text: Code Examples
        - href: blog.qmd
          text: Blog Posts
          
format:
  html:
    theme:
      - mystyles.scss
    mainfont: Verdana
    toc: true

editor: visual

