project:
  type: website
  output-dir: docs

website:
  logo: "catalina_selfie.png"
  title: "Jessica French"
  navbar:
      left:
        - href: index.qmd
          text: Home
        - href: about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

